### ISSUE TITLE
Install for GitLab workflow

### ISSUE THREAD

**Issue by jasonpatrickellykrause** [rbardini/resumed#1]
To get resumed to work on the CLI, I had to install it globally. 

```YAML
      - name: Export resume as HTML
        run: |
          npm install resumed -g
          npm install jsonresume-theme-even
          npm audit fix        
          resumed validate resume.json
          resumed render resume.json --theme even --output index.html
 ```

**Comment by rbardini** [comment]
Hi @jasonpatrickellykrause! That's interesting... What happens if you _don't_ install it globally?

I wouldn't expect global installation to be required—or even work, as it affects theme discovery. But then again, I have no experience with GitLab CI.

**Comment by jasonpatrickellykrause** [comment]
The install appears to work, but then "resumed" cannot be called. I was able to repro locally as well, but I am not an expert here.

**Comment by oreilles** [comment]
If you install `resumed` locally, you won't be able to just call `resumed` as it wouldn't be in your `PATH`. Instead, you can use it with `npx resumed` from the working directory without issue.

**Comment by p2635** [comment]
I also realized this a day or two ago, it doesn't just apply to resumed but any package you install locally

**Comment by rbardini** [comment]
That's correct, the instructions assume `resumed` is invoked with npx or through an npm script, as in [examples](https://github.com/rbardini/resumed/tree/master/examples).
