### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by alicescfernandes** [rbardini/resumed#13]
Hi! @rbardini! I was wondering how to use custom themes with resumed. This was a  feature on resume-cli, and allows me to have a custom template that i can modify as i wish, however it doesn't seem to work with resumed

```sh
❯ yarn test
yarn run v1.22.22
$ resumed render --theme jsonresume-theme-custom
jsonresume-theme-custom
Could not load theme jsonresume-theme-custom. Is it installed?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any thoughts on how i can get this working with resumed?

**Comment by rbardini** [comment]
Hi @alicescfernandes! You can follow the [local theme example](https://github.com/rbardini/resumed/tree/master/examples/with-local-theme). Basically, treat your custom (local) theme as a regular package dependency:

https://github.com/rbardini/resumed/blob/7d23b743b3c5df2890ff006bedc744c6fe49b166/examples/with-local-theme/package.json#L6-L9

**Comment by alicescfernandes** [comment]
Yep! I found thatwhile perusing this JSON theme [rbardini/jsonresume-theme-even](https://github.com/rbardini/jsonresume-theme-even/tree/main), but instead of pointing to a folder, i used yarn workspaces! 

Many thanks!
