### ISSUE TITLE
Feature Request: Subtitles within sections

### ISSUE THREAD

**Issue by BeauCranston** [rbardini/resumed#15]
Primarily for work experience, instead of just having highlights, it would be better if I could have sub titles to categorize the highlights and separate them out in a logical way.

**Comment by rbardini** [comment]
Hi @BeauCranston! Resumed is just a JSON Resume builder, it doesn't define the [schema](https://github.com/jsonresume/resume-schema) nor how resumes are rendered, which depends on the theme.

If you use [jsonresume-theme-even](https://github.com/rbardini/jsonresume-theme-even), you may be able to achieve that by writing Markdown in the `work.summary` field.
