### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by p2635** [rbardini/resumed#2]
Hi there, it's the first time I'm trying out `https://github.com/rbardini/resumed/tree/master/examples/with-pdf-export` so forgive me as I'm a beginner. I get the following error but not sure what I've done wrong, any help is appreciated.

```
user@thinkpad:~/Downloads/testing/test$ npm start

> start
> node index.js

file:///home/user/Downloads/testing/test/index.js:6
const resume = JSON.parse(await fs.readFile('resume.json', 'utf-8'))
                          ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
user@thinkpad:~/Downloads/testing/test$ 

```

**Comment by rbardini** [comment]
Hi @p2635! What Node.js version are you using? This example relies on [top level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await), which is supported from 14.8.0.

**Comment by p2635** [comment]
Followed the steps in https://phoenixnap.com/kb/update-node-js-version and solved my issue, thanks
