### ISSUE TITLE
`resumed init` gives a bad url to `meta.canonical`

### ISSUE THREAD

**Issue by etu** [rbardini/resumed#8]
Heya,

I'm the author of https://github.com/TaserudConsulting/jsonresume-nix that uses nix to package jsonresume themes and uses `resumed` to do reproducible builds of resumes. It recently came to my attention in the form of a Pull Request (https://github.com/TaserudConsulting/jsonresume-nix/pull/3) that the `meta.canonical` URL that I used in my samples were wrong. This was interesting to me since I had just used `resumed init` to get my sample.

So I dug a bit further, this package depends on `resume-schema` of version 1.0.0. The filename of the schema in 1.0.0 was `resume.json` on the master branch. However, after the release of 1.0.0 they have *changed* this filename on master to `schema.json`. However... they haven't made a new release of `resume-schema.

So as I see it, there's two things that needs to be done:
1. `resume-schema` must tag a new release
2. `resumed` can update this dependency and tag a new release

I will also report this to `json-resume`.

**Comment by rbardini** [comment]
Thanks, @etu! Once this is fixed in resume-schema, I'll release a new version with the updated dependency.

**Comment by rbardini** [comment]
Fixed in 84fd767374aecc625efaa5942b5b4d5fdf3936ee.
